### PR TITLE
Basic Android tests

### PR DESCRIPTION
**Pull request by nshuba**
Task/Issue URL: https://app.asana.com/0/0/1203585107010295/f

### Description
Basic Android tests for netguard

### Steps to test this PR
- [x] pull this branch
- [x] cd android
- [x] ./gradlew assemble
- [x] verify aar libraries are generated
- [x] cd ../android-test
- [x] ./gradlew connectedDebugAndroidTest
- [x] verify tests pass
- [ ] smoke test appTP as described in related PR: https://github.com/duckduckgo/Android/pull/2728

### CODE REVIEW

**Review by aitorvs — COMMENTED** [review]
The PR seems to have a lot of changes that I am not sure are needed.

* I think all resource files should be removed. I don't see a reason to have those
* the android module is now an application module, it shouln't
* Not entirely sure about the code structure, ie. the models are inside the `android` module however the native library (which relies on the models) are now in a different folder tree.
* netguardtester is a module inside `android`. I don't think it should

**Comment by nshuba** [comment]
> * I think all resource files should be removed. I don't see a reason to have those

I wasn't sure about them either. Removed now!

> * the android module is now an application module, it shouln't

Fixed!

> * Not entirely sure about the code structure, ie. the models are inside the `android` module however the native library (which relies on the models) are now in a different folder tree.

I am not a fan of the structure either. I think the C code should also be inside `android`. Should I make that change now?

> * netguardtester is a module inside `android`. I don't think it should

`netguardtester` relies on `netguard`, which is inside `android`. I can move it out and replace the `implementation project(":netguard")` dependency with a hard-coded path to the netguard AAR. Is that preferrable?

**Comment by aitorvs** [comment]
> I am not a fan of the structure either. I think the C code should also be inside `android`. Should I make that change now?
> `netguardtester` relies on `netguard`, which is inside `android`. I can move it out and replace the `implementation project(":netguard")` dependency with a hard-coded path to the netguard AAR. Is that preferrable?

I think i't s ok to have netguard `src` folder at the same level as `android`. `netguardtester` should not be inside `android` imo, it's not part of that. What I'd suggest is:
* rename `netguardtester` to `android-test`
* move `android-test` at the same (root) level as `android` and `src` native code
  * `android-test` is basically a copy of `android` that has the Kotlin models and the tests — doing it like this we also avoid any modification in the Android repo for now.

I can give it a go if you want me to

**Comment by nshuba** [comment]
I see. Instead of linking, we are re-compiling the netguard code to test it. I think it's ok for now. 

In the future, I would prefer to:

1. Avoid having to modify 2 CMakeLists.txt every time we add a source file to netguard
2. Keep the Kotlin models and a JNI interface together with the netguard AAR build

**Comment by aitorvs** [comment]
> 1. Avoid having to modify 2 CMakeLists.txt every time we add a source file to netguard
> 2. Keep the Kotlin models and a JNI interface together with the netguard AAR build
Both agree. However for 2/ I'd like to think about that public interface a bit more. I don't think we're in a rush for it tbh. And for 1/ I don't think it'll cause a lot of issues for right now

**Review by aitorvs — APPROVED** [review]

**Pull request merged**
